-- Sync artisan portrait and workshop media
begin;

update public.partners set portrait_url = '/partners/vaidava-ceramics/images/media/vaidava-ceramics-portrait.jpg', workshop_images = '["/partners/vaidava-ceramics/images/media/vaidava-ceramics-workshop-01.jpg", "/partners/vaidava-ceramics/images/media/vaidava-ceramics-workshop-02.jpg"]'::jsonb where slug = 'vaidava-ceramics';
update public.artisans set portrait_url = '/partners/vaidava-ceramics/images/media/vaidava-ceramics-portrait.jpg', workshop_images = '["/partners/vaidava-ceramics/images/media/vaidava-ceramics-workshop-01.jpg", "/partners/vaidava-ceramics/images/media/vaidava-ceramics-workshop-02.jpg"]'::jsonb where slug = 'vaidava-ceramics';
update public.partners set portrait_url = '/partners/cepli/images/media/cepli-portrait.jpg', workshop_images = '["/partners/cepli/images/media/cepli-workshop-01.jpg", "/partners/cepli/images/media/cepli-workshop-02.jpg", "/partners/cepli/images/media/cepli-workshop-03.jpg"]'::jsonb where slug = 'cepli';
update public.artisans set portrait_url = '/partners/cepli/images/media/cepli-portrait.jpg', workshop_images = '["/partners/cepli/images/media/cepli-workshop-01.jpg", "/partners/cepli/images/media/cepli-workshop-02.jpg", "/partners/cepli/images/media/cepli-workshop-03.jpg"]'::jsonb where slug = 'cepli';
update public.partners set portrait_url = '/partners/cerannic/images/media/cerannic-portrait.jpg', workshop_images = '["/partners/cerannic/images/93b0b19bd9d005.jpg", "/partners/cerannic/images/c4badaee2e25c1.png", "/partners/cerannic/images/739141683668e9.jpeg"]'::jsonb where slug = 'cerannic';
update public.artisans set portrait_url = '/partners/cerannic/images/media/cerannic-portrait.jpg', workshop_images = '["/partners/cerannic/images/93b0b19bd9d005.jpg", "/partners/cerannic/images/c4badaee2e25c1.png", "/partners/cerannic/images/739141683668e9.jpeg"]'::jsonb where slug = 'cerannic';
update public.partners set portrait_url = '/partners/latvijas-labumu-tirgus-mals/images/media/latvijas-labumu-tirgus-mals-portrait.jpg', workshop_images = '["/partners/latvijas-labumu-tirgus-mals/images/media/latvijas-labumu-tirgus-mals-workshop-01.jpeg", "/partners/latvijas-labumu-tirgus-mals/images/media/latvijas-labumu-tirgus-mals-workshop-02.jpeg"]'::jsonb where slug = 'latvijas-labumu-tirgus-mals';
update public.artisans set portrait_url = '/partners/latvijas-labumu-tirgus-mals/images/media/latvijas-labumu-tirgus-mals-portrait.jpg', workshop_images = '["/partners/latvijas-labumu-tirgus-mals/images/media/latvijas-labumu-tirgus-mals-workshop-01.jpeg", "/partners/latvijas-labumu-tirgus-mals/images/media/latvijas-labumu-tirgus-mals-workshop-02.jpeg"]'::jsonb where slug = 'latvijas-labumu-tirgus-mals';
update public.partners set portrait_url = '/partners/raibi-koki/images/raibi-koki-lielais-raibis-43x27-cm-03.png', workshop_images = '["/partners/raibi-koki/images/raibi-koki-triskasu-32x23-cm-01.png", "/partners/raibi-koki/images/raibi-koki-triskrasu-40x26-cm-02-01.png"]'::jsonb where slug = 'raibi-koki';
update public.artisans set portrait_url = '/partners/raibi-koki/images/raibi-koki-lielais-raibis-43x27-cm-03.png', workshop_images = '["/partners/raibi-koki/images/raibi-koki-triskasu-32x23-cm-01.png", "/partners/raibi-koki/images/raibi-koki-triskrasu-40x26-cm-02-01.png"]'::jsonb where slug = 'raibi-koki';
update public.partners set portrait_url = '/partners/studio-natural/images/media/studio-natural-portrait.jpg', workshop_images = '["/partners/studio-natural/images/media/studio-natural-workshop-01.jpg", "/partners/studio-natural/images/media/studio-natural-workshop-02.jpg"]'::jsonb where slug = 'studio-natural';
update public.artisans set portrait_url = '/partners/studio-natural/images/media/studio-natural-portrait.jpg', workshop_images = '["/partners/studio-natural/images/media/studio-natural-workshop-01.jpg", "/partners/studio-natural/images/media/studio-natural-workshop-02.jpg"]'::jsonb where slug = 'studio-natural';

commit;
